### ISSUE TITLE
BUG: Closed? labelled PR got stale message

### ISSUE THREAD

**Issue by bsipocz** [pllim/action-astropy-stalebot#4]
I believe this PR should have got the other comment due to its `Close?` label, and not because it's stale:

https://github.com/astropy/astropy/pull/11940

**Comment by pllim** [comment]
Yes, this is deliberate. To be more consistent with how issues are handled, "Close?" means stale now. When a PR becomes stale, it gets slapped a "Close?" label + warning.

Now, a human can also fast-track the staleness by manually applying the "Close?" label. In this case, the bot will warn but not do anything to do the label, which is the case for astropy/astropy#11940 .

So, this is not a bug. But we can discuss alternatives if you do not like this logic.

**Comment by bsipocz** [comment]
Nope, the logic is good, I quite like that `Close?` means fast-tracked stale status. I suppose we may just document it somewhere, so we can point to it (as in the past the close? ones got a warning too, so closing those PRs may surprise people. Or may not, I don't know, but a very short paragraph in the dev docs would cover us very well that this is the policy).

One other thing that I should probably just check in the code:
 - if a warning is added along with the label, but maintainers remove the Close? label, the bot would still close the PR in 30days, right? So the removal of an added `Close?` is not equivalent of adding a `keep-open`?
 (I still, very firmly believe that the artificial keeping PRs open approach should be minimized, so we should use the label very sparingly for cases where there is a good tech reason why the PR should be kept stale. Not having time to finish up is not such reason.

**Comment by pllim** [comment]
> if a warning is added along with the label, but maintainers remove the Close? label, the bot would still close the PR in 30days, right? So the removal of an added `Close?` is not equivalent of adding a `keep-open`?

Actually, no. Theoretically, it will go like this:

1. Bot adds `Close?` label + warning.
2. Maintainer remove `Close?`.
3. Bot sees it again and slap the `Close?` back on without warning.
4. Next time bot runs, it gets to the "handle stale" logic block. Because label was added (again) after warning, it will warn again.

This is still not equivalent of `keep-open`, as the bot will keep trying to re-stale it instead of leaving it alone.

> document it somewhere

Good idea but I am not sure where... a new section in https://docs.astropy.org/en/latest/#developer-documentation ?

**Comment by pllim** [comment]
p.s. Feel free to double check the stale logic in the code too! I might have missed something. Thanks!

**Comment by bsipocz** [comment]
> Actually, no. Theoretically, it will go like this:

And, so the 30 days start ticking from the first warning, right?

**Comment by pllim** [comment]
No, I think it is 30 days from the *last* warning.

https://github.com/pllim/action-astropy-stalebot/blob/5a7a41cd1820131ec5f9283cf5463fb83ad939f8/stale_pull_requests.py#L187-L190

But if a maintainer sees that the bot is playing tug of war with the person who keeps removing the stale label, maybe maintainer can just step in and manually close the PR. 😆

**Comment by bsipocz** [comment]
> Good idea but I am not sure where... a new section in https://docs.astropy.org/en/latest/#developer-documentation ?

Ideally I can see a QC/QA docs, but to keep it the simples and lowest effort maybe a few lines in a new heading in https://docs.astropy.org/en/latest/development/workflow/maintainer_workflow.html would suffice to have the logic bulletpoints listed for the stale checks.

**Comment by pllim** [comment]
> new heading

Okay, I'll see if I can find some time next week. Will ping you when PR is ready. 😄

**Comment by pllim** [comment]
Well, I don't think "next week" is happening. I'll open issue on astropy proper about the documentation.

**Comment by pllim** [comment]
Let's continue the discussion, if needed, at astropy/astropy#12156. Thanks for all the valuable feedback! 😸
