### ISSUE TITLE
BUG: PRs got missed out from run

### ISSUE THREAD

**Issue by bsipocz** [pllim/action-astropy-stalebot#6]
E.g. PR https://github.com/astropy/astropy/pull/10357 was included in the dry run, but I see no trace  of it in this morning's log, nor a stale warning on the PR

**Comment by pllim** [comment]
The bot choked on processing astropy/astropy#11597 . You can see the traceback in https://github.com/astropy/astropy/runs/3503024567?check_suite_focus=true . As a result, the rest of the queue got thrown out. I fixed the underlying problem in 5223c0e and 011a67d.

**Comment by bsipocz** [comment]
> You can see the traceback in https://github.com/astropy/astropy/runs/3503024567?check_suite_focus=true . As a result, the rest of the queue got thrown out. 

Ah, ok. It confused me as the log kept on going, so I assumed that all checks are independent and the exception just affected the checks for that one PR. My bad of not checking the actual code 😅

**Comment by pllim** [comment]
No worries!

**Comment by pllim** [comment]
And thanks for doing a sanity check on the bot!
