### ISSUE TITLE
Why was astropy PR 11693 closed?

### ISSUE THREAD

**Issue by karlwessel** [pllim/action-astropy-stalebot#8]
PR https://github.com/astropy/astropy/pull/11693 was closed by the bot "because of his previous message". That message was from over four months ago and said that it would close the PR within 30 days if the PR wasn't rebased. The PR was rebased within those 30 days.

**Comment by pllim** [comment]
Please see https://github.com/astropy/astropy/pull/11693#issuecomment-1066133766 for an explanation. Sorry for the confusion!
